### ISSUE TITLE
How to connect to ArcGIS Online using an organizational account?

### ISSUE THREAD

**Issue by gisfromscratch** [davetimmins/Anywhere.ArcGIS#12]
Is there any sample regarding ArcGIS Online? I always receive HTTP 404 using PortalGateway and ArcGISOnlineGateway. The unit tests are not functional?

**Comment by davetimmins** [comment]
I didn't include any ArcGIS Online tests as I didn't want to include services from my account due to usage credits etc. Typically you would still use the `PortalGateway` when working with services hosted on ArcGIS Online and only the `ArcGISOnlineGateway` when doing things against the AGOL REST endpoints e.g. search for data in a group.

If the service is secured you can pass in the token provider for ArcGIS Online so it would be something like

```c#
var gateway = new PortalGateway("https://services1.arcgis.com/HOHU5T5eRL3tLEDV/arcgis", tokenProvider: new ArcGISOnlineTokenProvider("username", "password"));
```

**Comment by davetimmins** [comment]
And to run the unit tests you can follow the instructions at https://xunit.github.io/docs/getting-started-dotnet-core.html#run-tests-visualstudio or there is the option to do it from a cmd prompt too using dotnet xunit if you set it up.

**Comment by gisfromscratch** [comment]
Works like a charm now, thanks

**Comment by davetimmins** [comment]
This is also now working for the static [`PortalGateway.Create`](https://github.com/davetimmins/Anywhere.ArcGIS/blob/master/src/Anywhere.ArcGIS/PortalGateway.cs#L28) method in v1.2.1 too

e.g. `var gateway = await PortalGateway.Create("https://services1.arcgis.com/HOHU5T5eRL3tLEDV/arcgis", "username", "password");`
