### ISSUE TITLE
Question - Conceivable to implement an OGC Gateway?

### ISSUE THREAD

**Issue by ca0v** [davetimmins/Anywhere.ArcGIS#20]
I wish I came across this project earlier in my development phase.  I created something similar but not nearly as good as what I'm seeing here.  One of my requirements is to hide WFS and WMS services behind and AGS API.  If I'm understanding this project correctly, I could fill that requirement is there was such a thing as an OgcGateway.  I don't have a question per-se, but would love to hear your comments and thoughts on this.

**Comment by davetimmins** [comment]
Hi, I typically use this project as more of a consumption rather than hosting type scenario though in the past I have done some work taking data from various sources and pushing it into Esri feature services (ETL type work) which could be an option here. If you're wanting to do hosting it may be worth looking at https://github.com/koopjs/koop there's a WFS plugin for that too https://github.com/koopjs/koop-output-wfs

**Comment by ca0v** [comment]
If I wanted to consume a WFS service via an AGS protocol, you think an OgcGateway isn't a good fit?  It seems like implementing SiteReport, could call GetCapabilities to get the "folders" and "service" information.  Likewise, DescribeLayer would be a wrapper for DescribeFeatureType, etc.  Unless I missed your meaning, this is not a hosting scenario as much as it is an AGS proxy for OGC services.  I think that's exactly what Anywhere.ArcGIS is for AGS services.  I'm not wanting to move data to ESRI but I am wanting to access GeoServer/MapServer data as if it were hosted in an ESRI server.

I'm looked at koop but I was needing a C# solution.  Also, koop looks complicated to configure so keeping things in a single solution platform would be better for me.

**Comment by davetimmins** [comment]
Sorry for the delay I missed your reply.

> I'm not wanting to move data to ESRI but I am wanting to access GeoServer/MapServer data as if it were hosted in an ESRI server.

That's why I mentioned Koop, as that is what that project provides. Using this lib it would be possible to get what you're wanting but it doesn't have all the operations that are part of the Esri REST API and some of the operations only have certain parts of the payload in them so it really depends on how you will consume the services. It sounds like you have full control over the solution though so I think technically yes, you would be able to do it. If you want to stick to C# then another option could be [SharpMap](https://github.com/SharpMap/SharpMap), that has WFS support I believe. It may be worth using both, so this lib as the interface and SharpMap as the implementation.

**Comment by ca0v** [comment]
Yes, I do want to remain in C# and that's where I was headed (I studied the SharpMap code extensively).  It's good to hear confirmation from you that it is a plausible solution.  For now I'm starting with `OgcGateway : API.IPortalGateway`, but ideally it would share an interface with a higher-level gateway (maybe PortalGatewayBase).  The WFS Koop extension seems to be [lightly implemented](https://github.com/koopjs/koop-output-wfs/blob/master/src/operations/describeFeatureType.js), but Node isn't really an option anway.  I really enjoy reading through your code.  Thank you!
